import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { User, FileText, Calendar, Download, CheckCircle, XCircle, Eye } from 'lucide-react';
import { StatutLivrable } from '../../models';
import { formatDate, getStatutLivrableBadge } from './utils';
export const LivrableItem = ({ livrable, onValider, onRejeter, onDownload, canEdit = true }) => {
    return (_jsx("div", { className: "bg-white border border-gray-200 p-6", children: _jsxs("div", { className: "flex items-start justify-between mb-4", children: [_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx("h3", { className: "font-semibold text-gray-900", children: livrable.titre }), getStatutLivrableBadge(livrable.statut)] }), _jsxs("div", { className: "flex items-center gap-4 text-sm text-gray-600 mb-2", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(User, { className: "h-4 w-4" }), livrable.etudiant.prenom, " ", livrable.etudiant.nom] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(FileText, { className: "h-4 w-4" }), livrable.nomFichier] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Calendar, { className: "h-4 w-4" }), formatDate(livrable.dateSubmission)] })] }), livrable.feedback && (_jsx("div", { className: "mt-2 p-3 bg-blue-50 border border-blue-200", children: _jsxs("p", { className: "text-sm text-gray-700", children: [_jsx("span", { className: "font-medium", children: "Feedback:" }), " ", livrable.feedback] }) }))] }), _jsxs("div", { className: "flex items-center gap-2 ml-4", children: [canEdit && livrable.statut === StatutLivrable.EN_ATTENTE_VALIDATION && (_jsxs(_Fragment, { children: [_jsxs("button", { onClick: () => onValider(livrable), className: "px-4 py-2 bg-primary text-white hover:bg-primary-dark transition-colors flex items-center gap-2", children: [_jsx(CheckCircle, { className: "h-4 w-4" }), "Valider"] }), _jsxs("button", { onClick: () => onRejeter(livrable), className: "px-4 py-2 bg-gray-600 text-white hover:bg-gray-700 transition-colors flex items-center gap-2", children: [_jsx(XCircle, { className: "h-4 w-4" }), "Rejeter"] })] })), _jsx("button", { onClick: () => {
                                // Ouvrir le livrable dans un nouvel onglet pour visualisation
                                const cheminFichier = `/documents/${livrable.nomFichier}`;
                                window.open(cheminFichier, '_blank');
                            }, className: "p-2 text-gray-600 hover:bg-gray-100 transition-colors", title: "Visualiser", children: _jsx(Eye, { className: "h-5 w-5" }) }), _jsx("button", { onClick: () => onDownload(livrable), className: "p-2 text-gray-600 hover:bg-gray-100 transition-colors", title: "T\u00E9l\u00E9charger", children: _jsx(Download, { className: "h-5 w-5" }) })] })] }) }));
};
