import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MessageSquare, FileText, Users, BookOpen, BarChart3 } from 'lucide-react';
export const PanelTabs = ({ activeTab, onTabChange, unreadMessagesCount, tachesCount, dossiersCount, prelectureCount, suiviCount = 0 }) => {
    return (_jsx("div", { className: "border-b border-gray-200", children: _jsxs("nav", { className: "flex", children: [_jsxs("button", { onClick: () => onTabChange('messages'), className: `flex items-center px-6 py-4 text-sm font-medium border-b-2 transition-colors ${activeTab === 'messages'
                        ? 'border-primary text-primary bg-white'
                        : 'border-transparent text-slate-500 hover:text-primary-700 bg-slate-50'}`, children: [_jsx(MessageSquare, { className: "h-4 w-4 mr-2" }), "Messages", unreadMessagesCount > 0 && (_jsx("span", { className: "ml-2 px-2 py-0.5 text-xs font-medium rounded-full bg-primary-50 text-primary-700", children: unreadMessagesCount }))] }), _jsxs("button", { onClick: () => onTabChange('taches'), className: `flex items-center px-6 py-4 text-sm font-medium border-b-2 transition-colors ${activeTab === 'taches'
                        ? 'border-primary text-primary bg-white'
                        : 'border-transparent text-slate-500 hover:text-primary-700 bg-slate-50'}`, children: [_jsx(FileText, { className: "h-4 w-4 mr-2" }), "T\u00E2ches", _jsx("span", { className: "ml-2 px-2 py-0.5 text-xs font-medium rounded-full bg-slate-200 text-slate-600", children: tachesCount })] }), _jsxs("button", { onClick: () => onTabChange('dossiers'), className: `flex items-center px-6 py-4 text-sm font-medium border-b-2 transition-colors ${activeTab === 'dossiers'
                        ? 'border-primary text-primary bg-white'
                        : 'border-transparent text-slate-500 hover:text-primary-700 bg-slate-50'}`, children: [_jsx(Users, { className: "h-4 w-4 mr-2" }), "Supervision", _jsx("span", { className: "ml-2 px-2 py-0.5 text-xs font-medium rounded-full bg-slate-200 text-slate-600", children: dossiersCount })] }), _jsxs("button", { onClick: () => onTabChange('prelecture'), className: `flex items-center px-6 py-4 text-sm font-medium border-b-2 transition-colors ${activeTab === 'prelecture'
                        ? 'border-primary text-primary bg-white'
                        : 'border-transparent text-slate-500 hover:text-primary-700 bg-slate-50'}`, children: [_jsx(BookOpen, { className: "h-4 w-4 mr-2" }), "Pr\u00E9-lecture", prelectureCount > 0 && (_jsx("span", { className: "ml-2 px-2 py-0.5 text-xs font-medium rounded-full bg-primary-50 text-primary-700", children: prelectureCount }))] }), _jsxs("button", { onClick: () => onTabChange('suivi'), className: `flex items-center px-6 py-4 text-sm font-medium border-b-2 transition-colors ${activeTab === 'suivi'
                        ? 'border-primary text-primary bg-white'
                        : 'border-transparent text-slate-500 hover:text-primary-700 bg-slate-50'}`, children: [_jsx(BarChart3, { className: "h-4 w-4 mr-2" }), "Suivi", _jsx("span", { className: "ml-2 px-2 py-0.5 text-xs font-medium rounded-full bg-slate-200 text-slate-600", children: suiviCount })] })] }) }));
};
