import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Calendar, Clock, Trash2, EyeOff, Users } from 'lucide-react';
import { formatDate, getPrioriteBadge } from './utils';
export const TacheCommuneItem = ({ tache, onSupprimer, onDesactiver, canEdit = true }) => {
    const isActive = tache.active !== false; // Par défaut actif si non spécifié
    return (_jsx("div", { className: `bg-white border border-gray-200 p-4 ${!isActive ? 'opacity-60' : ''}`, children: _jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx("h3", { className: "font-semibold text-gray-900", children: tache.titre }), getPrioriteBadge(tache.priorite), !isActive && (_jsx("span", { className: "px-2 py-1 text-xs font-medium bg-gray-100 text-gray-600 rounded-md border border-gray-200", children: "D\u00E9sactiv\u00E9e" }))] }), _jsx("p", { className: "text-sm text-gray-600 mb-3", children: tache.description }), _jsxs("div", { className: "flex flex-wrap items-center gap-y-2 gap-x-4 text-xs text-gray-500", children: [_jsxs("span", { className: "flex items-center gap-1.5 bg-gray-50 px-2 py-1 rounded-md border border-gray-100", children: [_jsx(Calendar, { className: "h-3.5 w-3.5 text-gray-400" }), _jsxs("span", { children: ["Cr\u00E9\u00E9e le ", formatDate(tache.dateCreation)] })] }), tache.dateEcheance && (_jsxs("span", { className: "flex items-center gap-1.5 bg-blue-50/50 px-2 py-1 rounded-md border border-blue-100/50 text-blue-700", children: [_jsx(Clock, { className: "h-3.5 w-3.5" }), _jsxs("span", { children: ["\u00C9ch\u00E9ance: ", formatDate(tache.dateEcheance)] })] })), tache.assigneA && (_jsxs("span", { className: "flex items-center gap-1.5 bg-primary/5 px-2 py-1 rounded-md border border-primary/10 text-primary font-medium", children: [_jsx(Users, { className: "h-3.5 w-3.5" }), _jsxs("span", { children: ["Assign\u00E9 \u00E0: ", tache.assigneA] })] }))] })] }), canEdit && (_jsxs("div", { className: "flex items-center gap-2 ml-4", children: [onDesactiver && (_jsx("button", { onClick: () => onDesactiver(tache.id), className: `p-2 transition-colors ${isActive
                                ? 'text-gray-600 hover:bg-gray-50'
                                : 'text-blue-600 hover:bg-blue-50'}`, title: isActive ? 'Désactiver la tâche' : 'Réactiver la tâche', children: _jsx(EyeOff, { className: "h-5 w-5" }) })), _jsx("button", { onClick: () => onSupprimer(tache.id), className: "p-2 text-red-600 hover:bg-red-50 transition-colors", title: "Supprimer la t\u00E2che", children: _jsx(Trash2, { className: "h-5 w-5" }) })] }))] }) }));
};
