import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Calendar, Plus, CheckCircle } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Badge } from '../../components/ui/badge';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';
const AnneeAcademiqueSection = ({ annees, onActiver, onCloturer, onCreateClick }) => {
    return (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs(CardTitle, { className: "flex items-center", children: [_jsx(Calendar, { className: "h-6 w-6 mr-2 text-primary" }), "Ann\u00E9es Acad\u00E9miques"] }), _jsx(CardDescription, { children: "G\u00E9rez le cycle de vie des ann\u00E9es acad\u00E9miques" })] }), _jsxs(Button, { onClick: onCreateClick, children: [_jsx(Plus, { className: "h-4 w-4 mr-2" }), "Nouvelle Ann\u00E9e"] })] }) }), _jsx(CardContent, { children: _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4", children: annees.map((annee) => (_jsxs(motion.div, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, className: `border-2 rounded-lg p-4 transition-all ${annee.estActive ? 'border-primary bg-primary/10 shadow-md' : 'border-gray-200 bg-white hover:shadow-md'}`, children: [_jsxs("div", { className: "flex items-start justify-between mb-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-bold text-lg text-gray-900", children: annee.code }), _jsx("p", { className: "text-sm text-gray-600", children: annee.libelle })] }), annee.estActive && (_jsxs(Badge, { className: "bg-green-50 text-green-700 border-green-200", children: [_jsx(CheckCircle, { className: "h-3 w-3 inline mr-1" }), "Active"] }))] }), _jsxs("div", { className: "space-y-2 text-sm text-gray-600 mb-4", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Calendar, { className: "h-4 w-4 mr-2" }), _jsxs("span", { children: ["D\u00E9but: ", format(annee.dateDebut, 'dd/MM/yyyy', { locale: fr })] })] }), _jsxs("div", { className: "flex items-center", children: [_jsx(Calendar, { className: "h-4 w-4 mr-2" }), _jsxs("span", { children: ["Fin: ", format(annee.dateFin, 'dd/MM/yyyy', { locale: fr })] })] })] }), _jsxs("div", { className: "flex gap-2", children: [!annee.estActive && new Date() < annee.dateFin && (_jsx(Button, { variant: "default", size: "sm", onClick: () => onActiver(annee.idAnnee), children: "Activer" })), annee.estActive && (_jsx(Button, { variant: "destructive", size: "sm", onClick: () => onCloturer(annee.idAnnee), children: "Cl\u00F4turer" }))] })] }, annee.idAnnee))) }) })] }));
};
export default AnneeAcademiqueSection;
