import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FileCheck, Plus, BookOpen, Info } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Badge } from '../../components/ui/badge';
import { TypePeriodeValidation } from '../../models/commission/PeriodeValidation';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';
const PeriodeValidationSection = ({ periodesValidation, periodeValidationActive, onChangerPeriode, onCreateClick }) => {
    const getTypePeriodeValidationLabel = (type) => {
        switch (type) {
            case TypePeriodeValidation.VALIDATION_SUJETS:
                return 'Validation des Sujets';
            case TypePeriodeValidation.VALIDATION_CORRECTIONS:
                return 'Validation des Corrections';
            case TypePeriodeValidation.AUCUNE:
                return 'Aucune période active';
        }
    };
    return (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs(CardTitle, { className: "flex items-center", children: [_jsx(FileCheck, { className: "h-6 w-6 mr-2 text-primary" }), "P\u00E9riodes de Validation"] }), _jsx(CardDescription, { children: "G\u00E9rez les p\u00E9riodes de validation des sujets et des documents corrig\u00E9s. Une seule p\u00E9riode peut \u00EAtre active \u00E0 la fois." })] }), _jsxs(Button, { onClick: onCreateClick, children: [_jsx(Plus, { className: "h-4 w-4 mr-2" }), "Nouvelle P\u00E9riode"] })] }) }), _jsxs(CardContent, { children: [periodeValidationActive && (_jsx("div", { className: "mb-6 p-4 bg-primary/10 border-2 border-primary/20 rounded-lg", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(Badge, { className: "bg-primary text-white", children: "P\u00E9riode Active" }), _jsx("h3", { className: "font-bold text-lg text-gray-900", children: getTypePeriodeValidationLabel(periodeValidationActive.type) })] }), _jsxs("div", { className: "text-sm text-gray-600 space-y-1", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(FileCheck, { className: "h-4 w-4 mr-2" }), _jsxs("span", { children: ["D\u00E9but: ", format(periodeValidationActive.dateDebut, 'dd/MM/yyyy', { locale: fr })] })] }), periodeValidationActive.dateFin && (_jsxs("div", { className: "flex items-center", children: [_jsx(FileCheck, { className: "h-4 w-4 mr-2" }), _jsxs("span", { children: ["Fin: ", format(periodeValidationActive.dateFin, 'dd/MM/yyyy', { locale: fr })] })] }))] })] }), _jsx(Button, { variant: "destructive", size: "sm", onClick: () => onChangerPeriode(TypePeriodeValidation.AUCUNE), children: "D\u00E9sactiver" })] }) })), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsxs(Card, { className: (periodeValidationActive === null || periodeValidationActive === void 0 ? void 0 : periodeValidationActive.type) === TypePeriodeValidation.VALIDATION_SUJETS ? 'border-primary bg-primary/10' : '', children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center", children: [_jsx(BookOpen, { className: "h-5 w-5 mr-2 text-primary" }), "Validation des Sujets"] }) }), _jsx(CardContent, { children: periodesValidation
                                                    .filter(p => p.type === TypePeriodeValidation.VALIDATION_SUJETS)
                                                    .map((periode) => (_jsx("div", { className: "space-y-2", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "text-sm text-gray-600", children: [_jsx("div", { children: format(periode.dateDebut, 'dd/MM/yyyy', { locale: fr }) }), periode.dateFin && (_jsxs("div", { children: ["\u2192 ", format(periode.dateFin, 'dd/MM/yyyy', { locale: fr })] }))] }), periode.estActive ? (_jsx(Badge, { className: "bg-green-50 text-green-700 border-green-200", children: "Active" })) : (_jsx(Button, { variant: "outline", size: "sm", onClick: () => onChangerPeriode(TypePeriodeValidation.VALIDATION_SUJETS), children: "Activer" }))] }) }, periode.idPeriode))) })] }), _jsxs(Card, { className: (periodeValidationActive === null || periodeValidationActive === void 0 ? void 0 : periodeValidationActive.type) === TypePeriodeValidation.VALIDATION_CORRECTIONS ? 'border-primary bg-primary/10' : '', children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center", children: [_jsx(FileCheck, { className: "h-5 w-5 mr-2 text-orange-600" }), "Validation des Corrections"] }) }), _jsx(CardContent, { children: periodesValidation
                                                    .filter(p => p.type === TypePeriodeValidation.VALIDATION_CORRECTIONS)
                                                    .map((periode) => (_jsx("div", { className: "space-y-2", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "text-sm text-gray-600", children: [_jsx("div", { children: format(periode.dateDebut, 'dd/MM/yyyy', { locale: fr }) }), periode.dateFin && (_jsxs("div", { children: ["\u2192 ", format(periode.dateFin, 'dd/MM/yyyy', { locale: fr })] }))] }), periode.estActive ? (_jsx(Badge, { className: "bg-green-50 text-green-700 border-green-200", children: "Active" })) : (_jsx(Button, { variant: "outline", size: "sm", onClick: () => onChangerPeriode(TypePeriodeValidation.VALIDATION_CORRECTIONS), children: "Activer" }))] }) }, periode.idPeriode))) })] })] }), _jsx("div", { className: "mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg", children: _jsxs("div", { className: "flex items-start", children: [_jsx(Info, { className: "h-5 w-5 text-yellow-600 mr-2 mt-0.5" }), _jsxs("div", { className: "text-sm text-yellow-800", children: [_jsx("p", { className: "font-medium mb-1", children: "R\u00E8gle importante" }), _jsx("p", { children: "Les p\u00E9riodes de validation des sujets et des corrections ne peuvent pas \u00EAtre actives simultan\u00E9ment. Activer une p\u00E9riode d\u00E9sactivera automatiquement l'autre." })] })] }) })] })] })] }));
};
export default PeriodeValidationSection;
