import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
const CarteMemoire = ({ memoire, onClick }) => {
    return (_jsx(motion.div, { className: "bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-all transform hover:-translate-y-1 border border-gray-100 cursor-pointer", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -20 }, transition: { duration: 0.3 }, whileHover: { scale: 1.01 }, onClick: () => onClick(memoire), children: _jsxs("div", { className: "flex flex-row h-full", children: [_jsx("div", { className: "w-20 flex-shrink-0 bg-gradient-to-br from-primary-50 to-primary-100 flex items-center justify-center", children: _jsxs("div", { className: "flex flex-col items-center", children: [_jsx("span", { className: "material-icons text-primary text-3xl", children: "picture_as_pdf" }), _jsx("span", { className: "text-xs text-primary-700 font-medium mt-1", children: "PDF" })] }) }), _jsxs("div", { className: "flex-1 p-4 flex flex-col justify-between", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1.5 flex-wrap", children: [_jsx("span", { className: "bg-navy-50 text-navy-700 text-xs font-medium py-0.5 px-2 rounded", children: memoire.departement }), _jsx("span", { className: "bg-primary-50 text-primary text-xs font-medium py-0.5 px-2 rounded", children: memoire.annee })] }), _jsx("h3", { className: "text-base font-bold text-navy mb-1 line-clamp-1", children: memoire.titre }), _jsx("p", { className: "text-sm text-navy-700 mb-2 line-clamp-2", children: memoire.description })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "flex items-center", children: [_jsx("span", { className: "material-icons text-gray-400 text-sm mr-1", children: "person" }), _jsx("span", { className: "text-sm text-navy font-medium", children: memoire.auteur })] }), _jsxs("div", { className: "hidden sm:flex items-center", children: [_jsx("span", { className: "material-icons text-gray-400 text-xs mr-1", children: "school" }), _jsx("span", { className: "text-xs text-gray-600", children: memoire.formation })] })] }), _jsxs("button", { className: "text-primary hover:text-primary-700 text-sm font-medium flex items-center transition-colors", onClick: (e) => {
                                        e.stopPropagation();
                                        onClick(memoire);
                                    }, children: ["Consulter", _jsx("span", { className: "material-icons text-sm ml-0.5", children: "arrow_forward" })] })] })] })] }) }));
};
export default CarteMemoire;
